language: go

go:
  - "1.11.x"

env:
  - GO111MODULE=on

install:
  - go mod download

before_deploy:
  - go get -u github.com/laher/goxc
  - mkdir -p $TRAVIS_BUILD_DIR/dist
  - goxc -d=$TRAVIS_BUILD_DIR/dist -os="linux darwin windows" -arch="386 amd64" -tasks=clean-destination,xc,archive,rmbin

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/dist/**/*.{tar.gz,zip}"
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].*$"